### PR TITLE
Add Original Grass main and Grass Doodads SVGs

### PR DESCRIPTION
**Pull request by M0REKZ**
Check the little talk on Teeworlds Discord #general

I think this is a good place to archive those svgs

(btw im getting this error when trying to clone the git repo, and github did something on the readme when i edited it on the web 🥶, tried to fix it but the death_gr?n line still remains affected)
`error: unable to create file spikes/death_gr?n.png: Illegal byte sequence`
`Updating files: 100% (2481/2481), done.`
`fatal: unable to checkout working tree`
`warning: Clone succeeded, but checkout failed.`

### CODE REVIEW

**Comment by ChillerDragon** [comment]
I will look into the errors at some point. These mapres could also go here https://github.com/ddnet/ddnet-data-svg

**Comment by ChillerDragon** [comment]
Thanks @M0REKZ :)

**Comment by ChillerDragon** [comment]
BTW both svgs were never included like this in any teeworlds release. The grass main is missing the shadow from 0.6 and has parts of the 0.7 extensions but not all. The doodads have a mailbox that has never been released in any version. I will mark them as custom in the description but its cool to have the official working version for sure.

**Comment by M0REKZ** [comment]
>These mapres could also go here https://github.com/ddnet/ddnet-data-svg

Yeah, it could go there with some minor modifications for the extra/missing tiles

**Pull request merged**
